[project]
name = "ai-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abhijeet1710", email = "abhijeetkhamkar30@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.0",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-app = "ai_app:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "ai_app"
module-root = "src"